apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farminsight-backend-image-pvc
  namespace: farminsight
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
