apiVersion: v1
kind: PersistentVolume
metadata:
  name: farminsight-backend-image-pv
  namespace: farminsight
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/rclone-tucloud-etce-server-storage/Applications/Farminsight/Backend/Pictures
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - etce-cluster-0
