apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/admin/.local/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/admin/.local/bin/kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: yourtoken_changeme
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: init_bucket
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: etce
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: admin_changeme
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: admin
            - name: BASE_PATH
              value: /influxdb
          image: influxdb:latest
          name: influxdb
          ports:
            - containerPort: 8086
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-storage
      restartPolicy: Always
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-storage
