apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farminsight-backend-sqlite-pvc
  namespace: farminsight
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
