"""
Django settings for django_server project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j_qnae2dq2!wltq1%ca7gku^ol8o7^t9-1xg5)gjw*1kcl)!d8'

# Initialize environment variables
env = environ.Env()

# Development-specific environment variables
environ.Env.read_env(os.path.join(BASE_DIR, '.env.dev'))

INFLUXDB_CLIENT_SETTINGS = {
    'url': env('INFLUXDB_URL'),
    'token': env('INFLUXDB_INIT_TOKEN'),
    'org': env('DOCKER_INFLUXDB_INIT_ORG')
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
]

# Camera snapshot storage config
MEDIA_URL = '/'
MEDIA_ROOT = BASE_DIR
SITE_URL = env("SITE_URL", default="http://127.0.0.1:8000")

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'farminsight_dashboard_backend.apps.FarminsightDashboardBackendConfig',
    'rest_framework',
    'oauth2_provider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'django_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'farminsight_dashboard_backend' / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "django_server.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #    "hosts": [("127.0.0.1", 6379)],
        #},
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db2.sqlite3',
    }
}

# Matrix notification settings
MATRIX_HOMESERVER = env('MATRIX_HOMESERVER', default='')
MATRIX_USER = env('MATRIX_USER', default='')
MATRIX_PASSWORD = env('MATRIX_PASSWORD', default='')


# For logging in the console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'db_handler': {
            'level': 'INFO',
            'class': 'django_server.custom_logger.DatabaseLogHandler',
        },
        'matrix_handler': {
            'level': 'WARNING',  # Only send WARNING and above to Matrix to avoid spam
            'class': 'django_server.custom_logger.MatrixLogHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'farminsight_dashboard_backend': {
            'handlers': ['console', 'db_handler', 'matrix_handler'],
            'level': 'DEBUG',
            'propagate': False,
        }
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'farminsight_dashboard_backend.Userprofile'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

'''
These are required while the django backend itself is handling login, they wont be used when using an external identity service
'''
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:3000/')
LOGIN_URL = '/api/login/'

'''
OIDC_ENABLED, OIDC_ISS_ENDPOINT, OIDC_RSA_PRIVATE_KEY are required for using the django login.
RESOURCE_SERVER_INTROSPECTION_URL, RESOURCE_SERVER_INTROSPECTION_CREDENTIALS, OAUTH2_VALIDATOR_CLASS
are required to use an external identity service.

It may be possible to support both at the same time, but not sure what would be required for this.

See the notes in custom_oauth_validator.py for concerns about switching back and how to minimize impact and possibly
keep the old userprofile records intact on migration. 
'''
OAUTH2_PROVIDER = {
    'OIDC_ENABLED': True,
    'OIDC_ISS_ENDPOINT': env('OIDC_ISS_ENDPOINT', default='http://127.0.0.1:8000'),
    'OIDC_RSA_PRIVATE_KEY': open(os.path.join(BASE_DIR, 'oidc.key')).read(),
    'SCOPES': {"openid": ''},
    #'RESOURCE_SERVER_INTROSPECTION_URL': 'https://development-isse-identityserver.azurewebsites.net/connect/introspect',
    #'RESOURCE_SERVER_INTROSPECTION_CREDENTIALS': ('interactive', ''),
    #'OAUTH2_VALIDATOR_CLASS': 'farminsight_dashboard_backend.custom_oauth_validator.CustomOAuth2Validator',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'EXCEPTION_HANDLER': 'farminsight_dashboard_backend.exceptions.custom_exception_handler'
}

# 0 or negative for indefinite duration
API_KEY_VALIDATION_DURATION_DAYS = env('API_KEY_VALIDATION_DURATION_DAYS', default=30)


# How long until log messages and queue entries get deleted from the DB to avoid unnecessary bloat
DB_LOG_RETENTION_DAYS = env('DB_LOG_RETENTION_DAYS', default=7)
DB_QUEUE_RETENTION_DAYS = env('DB_QUEUE_RETENTION_DAYS', default=7)


# To send emails from the backend to notify users there needs to be a configured mail account
# on a smtp server that accepts pw authentication
# for gmail this means creating an app password
SMTP_SERVER_ADDRESS = env('SMTP_SERVER_ADDRESS', default='smtp.gmail.com')
SMTP_SENDER_MAIL = env('SMTP_SENDER_MAIL', default='')
SMTP_SENDER_PASSWORD = env('SMTP_SENDER_PASSWORD', default='')


