# Generated by Django 5.1.9 on 2025-11-21 12:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import farminsight_dashboard_backend.models.camera
import farminsight_dashboard_backend.models.controllable_action
import farminsight_dashboard_backend.models.fpf
import farminsight_dashboard_backend.models.growing_cycle
import farminsight_dashboard_backend.models.hardware
import farminsight_dashboard_backend.models.organization
import farminsight_dashboard_backend.models.sensor
import farminsight_dashboard_backend.utils.api_key_generator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllableAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('actionClassId', models.UUIDField()),
                ('isActive', models.BooleanField(default=False)),
                ('isAutomated', models.BooleanField(default=False)),
                ('maximumDurationSeconds', models.IntegerField(default=0)),
                ('additionalInformation', models.TextField(blank=True)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.controllable_action.get_order_index_default)),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='FPF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField(default=False)),
                ('sensorServiceIp', models.CharField(max_length=256)),
                ('apiKey', models.CharField(default=farminsight_dashboard_backend.utils.api_key_generator.generate_random_api_key, max_length=64)),
                ('apiKeyValidUntil', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.fpf.get_order_index_default)),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('houseNumber', models.CharField(max_length=16)),
                ('gatherForecasts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatedResourceId', models.UUIDField(blank=True, null=True)),
                ('logLevel', models.CharField(max_length=24)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('room_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.organization.get_order_index_default)),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=256)),
                ('systemRole', models.CharField(default='user', max_length=256)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActionTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('actionValueType', models.CharField(max_length=64)),
                ('actionValue', models.CharField(max_length=128)),
                ('triggerLogic', models.TextField()),
                ('description', models.TextField(null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='farminsight_dashboard_backend.controllableaction')),
            ],
        ),
        migrations.CreateModel(
            name='ActionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('startedAt', models.DateTimeField(null=True)),
                ('endedAt', models.DateTimeField(null=True)),
                ('value', models.TextField(null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.actiontrigger')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queueEntries', to='farminsight_dashboard_backend.controllableaction')),
            ],
        ),
        migrations.AddField(
            model_name='controllableaction',
            name='FPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='farminsight_dashboard_backend.fpf'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('modelNr', models.CharField(max_length=256)),
                ('resolution', models.CharField(max_length=256)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('snapshotUrl', models.CharField(max_length=256)),
                ('livestreamUrl', models.CharField(max_length=256)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.camera.get_order_index_default)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='farminsight_dashboard_backend.fpf')),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='GrowingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('plants', models.CharField(max_length=256)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.growing_cycle.get_order_index_default)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growingCycles', to='farminsight_dashboard_backend.fpf')),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.hardware.get_order_index_default)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='farminsight_dashboard_backend.fpf')),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.AddField(
            model_name='controllableaction',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='farminsight_dashboard_backend.hardware'),
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amountInKg', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('growingCycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='farminsight_dashboard_backend.growingcycle')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measuredAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farminsight_dashboard_backend.camera')),
            ],
        ),
        migrations.AddField(
            model_name='fpf',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farminsight_dashboard_backend.location'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membershipRole', models.CharField(max_length=256)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization'),
        ),
        migrations.CreateModel(
            name='ResourceManagementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('URL', models.CharField(max_length=256)),
                ('required_parameters', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('activeScenario', models.CharField(blank=True, max_length=256)),
                ('availableScenarios', models.JSONField(blank=True, default=list)),
                ('forecasts', models.JSONField(blank=True, default=list)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('controllable_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='farminsight_dashboard_backend.controllableaction')),
                ('resource_management_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='farminsight_dashboard_backend.resourcemanagementmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('unit', models.CharField(blank=True, max_length=256)),
                ('parameter', models.CharField(blank=True, max_length=256)),
                ('modelNr', models.CharField(blank=True, max_length=256)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('aggregate', models.BooleanField(default=False)),
                ('orderIndex', models.IntegerField(default=farminsight_dashboard_backend.models.sensor.get_order_index_default)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='farminsight_dashboard_backend.fpf')),
            ],
            options={
                'ordering': ['orderIndex'],
            },
        ),
        migrations.CreateModel(
            name='SingleUseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('valid_until', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lowerBound', models.FloatField(blank=True, null=True)),
                ('upperBound', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_location_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='fpf',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_fpf_name_per_organization'),
        ),
    ]
