# Generated by Django 5.1.2 on 2025-03-17 08:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0015_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('relatedResourceId', models.UUIDField(blank=True, null=True)),
                ('logLevel', models.CharField(max_length=24)),
                ('message', models.TextField()),
            ],
        ),
    ]
