# Generated by Django 5.1.2 on 2025-03-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0016_logmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='parameter',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
