# Generated by Django 5.1.2 on 2025-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0017_sensor_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='modelNr',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='parameter',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
