# Generated by Django 5.1.4 on 2025-04-07 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0018_alter_sensor_modelnr_alter_sensor_parameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('isPublic', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64)),
                ('houseNumber', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='fpf',
            name='unique_name_per_organization',
        ),
        migrations.RemoveField(
            model_name='fpf',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='farminsight_dashboard_backend.organization'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farminsight_dashboard_backend.location'),
        ),
        migrations.AddConstraint(
            model_name='fpf',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_fpf_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_location_name_per_organization'),
        ),
    ]
