# Generated by Django 5.1.8 on 2025-04-07 16:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0019_location_remove_fpf_unique_name_per_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware',
                                          to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='ControllableAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('actionClassId', models.UUIDField()),
                ('isActive', models.BooleanField(default=False)),
                ('isAutomated', models.BooleanField(default=False)),
                ('maximumDurationSeconds', models.IntegerField(default=0)),
                ('additionalInformation', models.TextField(blank=True)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='farminsight_dashboard_backend.fpf')),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='farminsight_dashboard_backend.hardware')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('actionValueType', models.CharField(max_length=64)),
                ('actionValue', models.CharField(max_length=128)),
                ('triggerLogic', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='farminsight_dashboard_backend.controllableaction')),
            ],
        ),
        migrations.CreateModel(
            name='ActionQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('startedAt', models.DateTimeField(null=True)),
                ('endedAt', models.DateTimeField(null=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.actiontrigger')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queueEntries', to='farminsight_dashboard_backend.controllableaction')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lowerBound', models.FloatField(blank=True, null=True)),
                ('upperBound', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Threshold', to='farminsight_dashboard_backend.sensor')),
            ],
        ),
    ]
