# Generated by Django 5.1.8 on 2025-04-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0020_hardware_controllableaction_actiontrigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
    ]
