# Generated by Django 5.1.8 on 2025-04-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0021_alter_threshold_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='isPublic',
            new_name='gatherForecasts',
        ),
        migrations.AddField(
            model_name='actionqueue',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actiontrigger',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farminsight_dashboard_backend.organization'),
        ),
    ]
