# Generated by Django 5.1.4 on 2025-05-13 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0022_rename_ispublic_location_gatherforecasts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='FPF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='farminsight_dashboard_backend.fpf'),
            preserve_default=False,
        ),
    ]
