# Generated by Django 5.1.4 on 2025-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0023_hardware_fpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='aggregate',
            field=models.BooleanField(default=False),
        ),
    ]
