# Generated by Django 5.1.9 on 2025-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0024_sensor_aggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='controllableaction',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fpf',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growingcycle',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hardware',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
    ]
