# Generated by Django 5.1.9 on 2025-06-11 13:22

import farminsight_dashboard_backend.models.camera
import farminsight_dashboard_backend.models.controllable_action
import farminsight_dashboard_backend.models.fpf
import farminsight_dashboard_backend.models.growing_cycle
import farminsight_dashboard_backend.models.hardware
import farminsight_dashboard_backend.models.organization
import farminsight_dashboard_backend.models.sensor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0025_camera_orderindex_controllableaction_orderindex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='controllableaction',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='fpf',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='growingcycle',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='logmessage',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AlterField(
            model_name='camera',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.camera.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='controllableaction',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.controllable_action.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='fpf',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.fpf.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='growingcycle',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.growing_cycle.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.hardware.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.organization.get_order_index_default),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.sensor.get_order_index_default),
        ),
    ]
