# Generated by Django 5.1.9 on 2025-11-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0027_singleusetoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farminsight_dashboard_backend.hardware'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='pingEndpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farminsight_dashboard_backend.hardware'),
        ),
    ]
