# Generated by Django 5.1.9 on 2025-12-10 08:19

import farminsight_dashboard_backend.models.resource_management_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0028_notification_resourcemanagementmodel_actionmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcemanagementmodel',
            options={'ordering': ['orderIndex']},
        ),
        migrations.AddField(
            model_name='fpf',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resourcemanagementmodel',
            name='orderIndex',
            field=models.IntegerField(default=farminsight_dashboard_backend.models.resource_management_model.get_order_index_default),
        ),
    ]
