# Generated by Django 5.1.2 on 2025-11-13 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0028_fpf_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpf',
            name='isActive',
        ),
        migrations.CreateModel(
            name='ResourceManagementModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('URL', models.CharField(max_length=256)),
                ('required_parameters', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=False)),
                ('intervalSeconds', models.IntegerField()),
                ('activeScenario', models.CharField(blank=True, max_length=256)),
                ('availableScenarios', models.JSONField(blank=True, default=list)),
                ('forecasts', models.JSONField(blank=True, default=list)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='farminsight_dashboard_backend.fpf')),
            ],
        ),
        migrations.CreateModel(
            name='ActionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100)),
                ('controllable_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_mappings', to='farminsight_dashboard_backend.controllableaction')),
                ('resource_management_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='farminsight_dashboard_backend.resourcemanagementmodel')),
            ],
        ),
    ]
