# Generated by Django 5.1.9 on 2025-12-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0028_camera_hardware_hardware_pingendpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllableaction',
            name='nextAction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farminsight_dashboard_backend.controllableaction'),
        ),
    ]
