# Generated by Django 5.1.2 on 2025-12-05 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Hier den Namen der existierenden 0029-Datei eintragen:
        ('farminsight_dashboard_backend', '0029_alter_resourcemanagementmodel_options_fpf_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpf',
            name='energyBatteryMaxWh',
            field=models.FloatField(default=1600.0, help_text='Maximum battery capacity in Wh (default 1.6kWh = 1600Wh)'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyGridConnectThreshold',
            field=models.FloatField(default=11.0, help_text='Battery percentage at which to connect to grid'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyGridDisconnectThreshold',
            field=models.FloatField(default=50.0, help_text='Battery percentage at which to disconnect from grid (when charging complete)'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyShutdownThreshold',
            field=models.FloatField(default=10.0, help_text='Battery percentage at which to shutdown non-critical consumers'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyWarningThreshold',
            field=models.FloatField(default=20.0, help_text='Battery percentage for warning status'),
        ),
        migrations.AddField(
            model_name='threshold',
            name='resourceManagementModel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.resourcemanagementmodel'),
        ),
        migrations.AddField(
            model_name='threshold',
            name='thresholdType',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('model', 'Model'), ('energy', 'Energy')], default='sensor', max_length=64),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
        migrations.CreateModel(
            name='EnergyConsumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('consumptionWatts', models.FloatField(help_text='Power consumption in watts')),
                ('priority', models.IntegerField(default=5, help_text='Priority level 1-10 (1=critical, 10=optional)')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumers', to='farminsight_dashboard_backend.fpf')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Other consumers that must be active for this consumer to operate', related_name='dependents', to='farminsight_dashboard_backend.energyconsumer')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('sourceType', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('grid', 'Grid'), ('battery', 'Battery'), ('generator', 'Generator')], max_length=64)),
                ('maxOutputWatts', models.FloatField(help_text='Maximum power output in watts')),
                ('currentOutputWatts', models.FloatField(default=0, help_text='Current power output in watts')),
                ('weatherDependent', models.BooleanField(default=False, help_text='Whether the output depends on weather conditions (e.g., solar, wind)')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_sources', to='farminsight_dashboard_backend.fpf')),
            ],
            options={
                'ordering': ['sourceType', 'name'],
            },
        ),
    ]
