# Generated by Django 5.1.9 on 2026-02-02 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0029_alter_resourcemanagementmodel_options_fpf_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpf',
            name='energyBatteryMaxWh',
            field=models.FloatField(default=1600.0, help_text='Maximum battery capacity in Wh (default 1.6kWh = 1600Wh)'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyGridConnectThreshold',
            field=models.FloatField(default=11.0, help_text='Battery percentage at which to connect to grid'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyGridDisconnectThreshold',
            field=models.FloatField(default=50.0, help_text='Battery percentage at which to disconnect from grid (when charging complete)'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyShutdownThreshold',
            field=models.FloatField(default=10.0, help_text='Battery percentage at which to shutdown non-critical consumers'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='energyWarningThreshold',
            field=models.FloatField(default=20.0, help_text='Battery percentage for warning status'),
        ),
        migrations.AddField(
            model_name='fpf',
            name='resourceManagementConfig',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resourcemanagementmodel',
            name='model_type',
            field=models.CharField(choices=[('energy', 'Energy'), ('water', 'Water')], default='energy', max_length=64),
        ),
        migrations.AddField(
            model_name='threshold',
            name='rMMForecastName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='threshold',
            name='resourceManagementModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.resourcemanagementmodel'),
        ),
        migrations.AddField(
            model_name='threshold',
            name='thresholdType',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
        migrations.CreateModel(
            name='EnergyConsumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('consumptionWatts', models.FloatField(help_text='Default/fallback power consumption in watts. If sensor is linked, live data will be used.')),
                ('priority', models.IntegerField(default=5, help_text='Priority level 1-10 (1=critical, 10=optional)')),
                ('shutdownThreshold', models.IntegerField(default=0, help_text='Battery percentage at which this consumer should be shut down (0 = never auto-shutdown, use global thresholds)')),
                ('forecastShutdownThreshold', models.IntegerField(default=0, help_text='Predicted battery % at which to schedule shutdown via AI forecast (0 = disabled)')),
                ('forecastBufferDays', models.IntegerField(default=0, help_text='Days before predicted threshold to execute shutdown action')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumers', to='farminsight_dashboard_backend.fpf')),
                ('controllableAction', models.ForeignKey(blank=True, help_text='Link to a controllable action for automatic on/off control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumers', to='farminsight_dashboard_backend.controllableaction')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Other consumers that must be active for this consumer to operate', related_name='dependents', to='farminsight_dashboard_backend.energyconsumer')),
                ('sensor', models.ForeignKey(blank=True, help_text='Link to a sensor for live power consumption measurement (e.g., Shelly power reading)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumers', to='farminsight_dashboard_backend.sensor')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('sourceType', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('grid', 'Grid'), ('battery', 'Battery'), ('generator', 'Generator')], max_length=64)),
                ('maxOutputWatts', models.FloatField(help_text='Maximum power output in watts')),
                ('currentOutputWatts', models.FloatField(default=0, help_text='Default/fallback current power output. If sensor is linked, live data will be used.')),
                ('weatherDependent', models.BooleanField(default=False, help_text='Whether the output depends on weather conditions (e.g., solar, wind)')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('FPF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_sources', to='farminsight_dashboard_backend.fpf')),
                ('controllableAction', models.ForeignKey(blank=True, help_text='Link to a controllable action for source control (e.g., grid connection switch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_sources', to='farminsight_dashboard_backend.controllableaction')),
                ('sensor', models.ForeignKey(blank=True, help_text='Link to a sensor for live power output measurement (e.g., solar inverter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_sources', to='farminsight_dashboard_backend.sensor')),
            ],
            options={
                'ordering': ['sourceType', 'name'],
            },
        ),
    ]
