# Generated by Django 5.1.9 on 2025-12-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0029_alter_resourcemanagementmodel_options_fpf_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='rMMForecastName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='threshold',
            name='resourceManagementModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.resourcemanagementmodel'),
        ),
        migrations.AddField(
            model_name='threshold',
            name='thresholdType',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
    ]
