# Generated by Django 5.1.2 on 2025-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0029_remove_fpf_isactive_resourcemanagementmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('room_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
