# Generated by Django 5.1.2 on 2025-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0030_fpf_energybatterymaxwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumer',
            name='shutdownThreshold',
            field=models.IntegerField(default=0, help_text='Battery percentage at which this consumer should be shut down (0 = never auto-shutdown, use global thresholds)'),
        ),
    ]
