# Generated by Django 5.1.9 on 2026-01-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0030_threshold_rmmforecastname_and_more'),
    ]

    operations = [
    ]
