# Generated by Django 5.1.2 on 2025-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpf',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
