# Generated by Django 5.1.2 on 2025-12-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0031_add_shutdown_threshold_to_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumer',
            name='controllableAction',
            field=models.ForeignKey(blank=True, help_text='Link to a controllable action for automatic on/off control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumers', to='farminsight_dashboard_backend.controllableaction'),
        ),
        migrations.AddField(
            model_name='energyconsumer',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Link to a sensor for live power consumption measurement (e.g., Shelly power reading)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_consumers', to='farminsight_dashboard_backend.sensor'),
        ),
        migrations.AddField(
            model_name='energysource',
            name='controllableAction',
            field=models.ForeignKey(blank=True, help_text='Link to a controllable action for source control (e.g., grid connection switch)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_sources', to='farminsight_dashboard_backend.controllableaction'),
        ),
        migrations.AddField(
            model_name='energysource',
            name='sensor',
            field=models.ForeignKey(blank=True, help_text='Link to a sensor for live power output measurement (e.g., solar inverter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='energy_sources', to='farminsight_dashboard_backend.sensor'),
        ),
        migrations.AlterField(
            model_name='energyconsumer',
            name='consumptionWatts',
            field=models.FloatField(help_text='Default/fallback power consumption in watts. If sensor is linked, live data will be used.'),
        ),
        migrations.AlterField(
            model_name='energysource',
            name='currentOutputWatts',
            field=models.FloatField(default=0, help_text='Default/fallback current power output. If sensor is linked, live data will be used.'),
        ),
    ]
