# Generated by Django 5.1.2 on 2025-12-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0032_add_sensor_action_links_to_energy_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='resourceManagementModel',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='thresholdType',
        ),
        migrations.AddField(
            model_name='resourcemanagementmodel',
            name='model_type',
            field=models.CharField(choices=[('energy', 'Energy'), ('water', 'Water')], default='energy', max_length=64),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
            preserve_default=False,
        ),
    ]
