# Generated by Django 5.1.2 on 2026-01-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0033_add_threshold_rmmforecastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemanagementmodel',
            name='model_type',
            field=models.CharField(blank=True, default='water', max_length=50),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='resourceManagementModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.resourcemanagementmodel'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='thresholdType',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
