# Generated by Django 5.1.2 on 2026-01-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0033_remove_threshold_resourcemanagementmodel_and_more'),
    ]

    operations = [
    ]
