# Generated by Django 5.1.2 on 2026-01-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0033_remove_threshold_resourcemanagementmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpf',
            name='resourceManagementConfig',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='threshold',
            name='rMMForecastName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='threshold',
            name='resourceManagementModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.resourcemanagementmodel'),
        ),
        migrations.AddField(
            model_name='threshold',
            name='thresholdType',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='farminsight_dashboard_backend.sensor'),
        ),
    ]
