# Generated by Django 5.1.15 on 2026-01-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0029_alter_resourcemanagementmodel_options_fpf_isactive_and_more'),
        ('farminsight_dashboard_backend', '0035_fpf_resourcemanagementconfig_and_more'),
    ]

    operations = [
    ]
