# Generated by Django 5.1.15 on 2026-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farminsight_dashboard_backend', '0036_merge_20260128_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumer',
            name='forecastBufferDays',
            field=models.IntegerField(default=0, help_text='Days before predicted threshold to execute shutdown action'),
        ),
        migrations.AddField(
            model_name='energyconsumer',
            name='forecastShutdownThreshold',
            field=models.IntegerField(default=0, help_text='Predicted battery % at which to schedule shutdown via AI forecast (0 = disabled)'),
        ),
    ]
